### PR TITLE
Linux fixes

### PR DESCRIPTION
**Pull request by ChristophHaag**
These are two obvious problems. The next one is a bit over my head:

```
/home/chris/build/Vulkan/base/vulkanShapes.hpp: In member function 'void vkx::ShapesRenderer::buildCommandBuffer()':
/home/chris/build/Vulkan/base/vulkanShapes.hpp:123:53: error: ambiguous overload for 'operator=' (operand types are 'vk::ClearDepthStencilValue' and '<brace-enclosed initializer list>')
             clearValues[1].depthStencil = { 1.0f, 0 };
                                                     ^
In file included from /home/chris/build/Vulkan/base/common.hpp:105:0,
                 from /home/chris/build/Vulkan/examples/windows/vr_common.hpp:1,
                 from /home/chris/build/Vulkan/examples/windows/vr_openvr.cpp:1:
/usr/include/vulkan/vulkan.hpp:3954:29: note: candidate: vk::ClearDepthStencilValue& vk::ClearDepthStencilValue::operator=(const VkClearDepthStencilValue&)
     ClearDepthStencilValue& operator=( VkClearDepthStencilValue const & rhs )
                             ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:3941:10: note: candidate: constexpr vk::ClearDepthStencilValue& vk::ClearDepthStencilValue::operator=(const vk::ClearDepthStencilValue&)
   struct ClearDepthStencilValue
          ^~~~~~~~~~~~~~~~~~~~~~
```
The exact same code compiles in Sascha Willems' upstream repository so not sure what goes wrong.

### CODE REVIEW

**Comment by jherico** [comment]
changing the line to ` clearValues[1].depthStencil = vk::ClearDepthStencilValue { 1.0f, 0 };` should resolve the ambiguity.  However, this PR includes a rename to one of the files that's a case-only change in the path.  Do you know why your version of `cmake/externals/openvr` is `cmake/externals/OpenVR`?

**Comment by ChristophHaag** [comment]
It's the other way around.

cmake/macros/TargetOpenVR.cmake contains `add_dependency_external_projects(OpenVR)` which then gets inserted into the path in cmake/macros/AddDependencyExternalProjects.cmake `add_subdirectory(${EXTERNAL_PROJECT_DIR}/${_PROJ_NAME} ${EXTERNALS_BINARY_DIR}/${_PROJ_NAME})`. Rather than trying to fixup the cmake files I though making the directory name adhere to the OpenVR name would be a smaller and simpler fix.

I'm not super familiar with the C++ syntax, so thanks for the hint. With these commits I get to

> [ 14%] Linking CXX executable ../bin/vr_openvr
> [ 14%] Built target vr_openvr

**Comment by ChristophHaag** [comment]
It actually works on the radv driver. Unfortunately performance is really bad because the compositor eats all cpu time until it segfaults (the steamvr compositor segfaults, not your example), so it's a bit weird.

It's cool that it runs at all though.

screenshot_20170615_004327

**Comment by jherico** [comment]
I will try to fix the CMake files.  I've had no end of problems when I've tried to make a case-only change to Git.

**Comment by jherico** [comment]
I've fixed the cmake files and merged the other changes after rebasing them without the name change commit.  Closing this PR as 4 out of the 5 commits are now incorporated.

**Pull request closed without merging**
